- name: Create ssh config
  hosts: all
  become: false
  vars:
    local_user: "{{ lookup('env', 'USER') }}"
    ssh_path: "~{{ local_user }}/.ssh"
    ssh_config_path: "{{ ssh_path }}/config"
    ssh_config_include_path: "{{ ssh_path }}/include"
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg:
          - "inventory_file = {{ inventory_file }} "
          - "remote_user = {{ remote_user | default ('remarkai-local') }}"
      ignore_errors: True

    - name: Ensure prerequisits
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      delegate_to: localhost
      run_once: True
      with_items:
        - stormssh
    - name: Ensure ssh config exists
      ansible.builtin.file:
        path: "{{ ssh_config_path }}"
        state: touch
      delegate_to: localhost
    - name: Ensure ssh config include
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_path }}"
        insertbefore: BOF
        line: "Include {{ ssh_config_include_path }}/*"
        state: present
      delegate_to: localhost
      run_once: True
    - name: Create ssh config
      community.general.ssh_config:
        ssh_config_file: "{{ ssh_config_include_path }}/{{ inventory_hostname }}"
        host: "{{ inventory_hostname }}"
        hostname: "{{ ansible_host }}"
        port: "{{ ansible_port | default(22) }}"
        remote_user: "{{ ansible_user | default ('remarkai-local') }}"
        # identity_file: "/home/akasurde/.ssh/id_rsa"
        state: present
      delegate_to: localhost


