- name: Install latest open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present
    update_cache: yes

- name: Enable and start iscsi daemon
  ansible.builtin.systemd:
    name: iscsid
    state: started
    enabled: yes
