- name: Install latest qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Enable and start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes
