- name: create groups
  import_tasks: create-groups.yml
  tags:
    - create-groups

- name: create users
  import_tasks: create-users.yml
  tags:
    - create-users

- name: disable root SSH access
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart sshd

- name: disable SSH password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart sshd

- name: allow agent forwarding to root
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    insertbefore: "^Defaults"
    line: "Defaults        env_keep+=SSH_AUTH_SOCK"
    state: present
