- name: create groups
  import_tasks: create-groups.yml
  tags:
    - create-groups

- name: create users
  import_tasks: create-users.yml
  tags:
    - create-users

- name: config ssh
  import_tasks: config-ssh.yml
  tags:
    - config-ssh
