- name: "{{ role_name }} > create-cloudimg-template | Check if cloudimg exist"
  ansible.builtin.command: "qm status {{ cloudimg_vmid }}"
  register: qm_status_output
  failed_when:
    - qm_status_output.rc != 0
    - qm_status_output.rc != 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Download cloudimg"
  ansible.builtin.get_url:
    url: "{{ cloudimg_download_url }}"
    dest: "{{ cloudimg_dest }}"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Create vm"
  ansible.builtin.command: "qm create {{ cloudimg_vmid }} --memory 2048 --core 2 --name ubuntu-cloud --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-pci"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Import disk to local-lvm and attach as a SCSI driver"
  ansible.builtin.command: "qm set {{ cloudimg_vmid }} --scsi0 local-lvm:0,import-from={{cloudimg_dest}}"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Add cloud-init CD-ROM drive"
  ansible.builtin.command: "qm set {{ cloudimg_vmid }} --ide2 local-lvm:cloudinit"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Set boot directly from img"
  ansible.builtin.command: "qm set {{ cloudimg_vmid }} --boot order=scsi0"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Set serial console"
  ansible.builtin.command: "qm set {{ cloudimg_vmid }} --serial0 socket --vga serial0"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Create tmp ssh pub key file"
  ansible.builtin.copy:
    content: "{{ cloudinit_sshkeys }}"
    dest: /tmp/sshkey.pub
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Set cloud-init config"
  ansible.builtin.command: "qm set {{ cloudimg_vmid }} --agent enabled=1 --ciuser {{ cloudinit_user }} --ipconfig0 ip=dhcp --sshkeys /tmp/sshkey.pub"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template

- name: "{{ role_name }} > create-cloudimg-template | Convert to template"
  ansible.builtin.command: "qm template {{ cloudimg_vmid }}"
  when: qm_status_output.rc  == 2
  run_once: True
  tags:
    - create-cloudimg-template
